# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: syncComputation.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15syncComputation.proto\"\"\n\nAddRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1d\n\x0b\x41\x64\x64Response\x12\x0e\n\x06result\x18\x01 \x01(\x05\" \n\x0bSortRequest\x12\x11\n\tinputList\x18\x01 \x03(\x05\"\"\n\x0cSortResponse\x12\x12\n\nsortedList\x18\x01 \x03(\x05\x32X\n\x0b\x63omputation\x12\"\n\x03\x41\x64\x64\x12\x0b.AddRequest\x1a\x0c.AddResponse\"\x00\x12%\n\x04Sort\x12\x0c.SortRequest\x1a\r.SortResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'syncComputation_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ADDREQUEST']._serialized_start=25
  _globals['_ADDREQUEST']._serialized_end=59
  _globals['_ADDRESPONSE']._serialized_start=61
  _globals['_ADDRESPONSE']._serialized_end=90
  _globals['_SORTREQUEST']._serialized_start=92
  _globals['_SORTREQUEST']._serialized_end=124
  _globals['_SORTRESPONSE']._serialized_start=126
  _globals['_SORTRESPONSE']._serialized_end=160
  _globals['_COMPUTATION']._serialized_start=162
  _globals['_COMPUTATION']._serialized_end=250
# @@protoc_insertion_point(module_scope)
