# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SyncFiles.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fSyncFiles.proto\"2\n\rFileOperation\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"3\n\x0fOperationResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2Q\n\x16SynchronizedFileSystem\x12\x37\n\x11SyncFileOperation\x12\x0e.FileOperation\x1a\x10.OperationResult\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SyncFiles_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILEOPERATION']._serialized_start=19
  _globals['_FILEOPERATION']._serialized_end=69
  _globals['_OPERATIONRESULT']._serialized_start=71
  _globals['_OPERATIONRESULT']._serialized_end=122
  _globals['_SYNCHRONIZEDFILESYSTEM']._serialized_start=124
  _globals['_SYNCHRONIZEDFILESYSTEM']._serialized_end=205
# @@protoc_insertion_point(module_scope)
