# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fileSystem.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x66ileSystem.proto\"6\n\rUploadRequest\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\x12\x13\n\x0b\x66ileContent\x18\x02 \x01(\x0c\"\"\n\x0eUploadResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"#\n\x0f\x44ownloadRequest\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\"\'\n\x10\x44ownloadResponse\x12\x13\n\x0b\x66ileContent\x18\x01 \x01(\x0c\"!\n\rDeleteRequest\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\"\"\n\x0e\x44\x65leteResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"9\n\rRenameRequest\x12\x13\n\x0boldFileName\x18\x01 \x01(\t\x12\x13\n\x0bnewFileName\x18\x02 \x01(\t\"\"\n\x0eRenameResponse\x12\x10\n\x08response\x18\x01 \x01(\t2\xe8\x01\n\x0cQ1FileSystem\x12\x33\n\x0eUploadFunction\x12\x0e.UploadRequest\x1a\x0f.UploadResponse\"\x00\x12\x39\n\x10\x44ownloadFunction\x12\x10.DownloadRequest\x1a\x11.DownloadResponse\"\x00\x12\x33\n\x0e\x44\x65leteFunction\x12\x0e.DeleteRequest\x1a\x0f.DeleteResponse\"\x00\x12\x33\n\x0eRenameFunction\x12\x0e.RenameRequest\x1a\x0f.RenameResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fileSystem_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UPLOADREQUEST']._serialized_start=20
  _globals['_UPLOADREQUEST']._serialized_end=74
  _globals['_UPLOADRESPONSE']._serialized_start=76
  _globals['_UPLOADRESPONSE']._serialized_end=110
  _globals['_DOWNLOADREQUEST']._serialized_start=112
  _globals['_DOWNLOADREQUEST']._serialized_end=147
  _globals['_DOWNLOADRESPONSE']._serialized_start=149
  _globals['_DOWNLOADRESPONSE']._serialized_end=188
  _globals['_DELETEREQUEST']._serialized_start=190
  _globals['_DELETEREQUEST']._serialized_end=223
  _globals['_DELETERESPONSE']._serialized_start=225
  _globals['_DELETERESPONSE']._serialized_end=259
  _globals['_RENAMEREQUEST']._serialized_start=261
  _globals['_RENAMEREQUEST']._serialized_end=318
  _globals['_RENAMERESPONSE']._serialized_start=320
  _globals['_RENAMERESPONSE']._serialized_end=354
  _globals['_Q1FILESYSTEM']._serialized_start=357
  _globals['_Q1FILESYSTEM']._serialized_end=589
# @@protoc_insertion_point(module_scope)
